---
- name: playbook 01
  hosts: webservers
  become: true
  tasks:
  - name: creating multiple users
    user:
      name: '{{ item }}'
      state: present
    with_items:
      - maheshbabu
      - praneetha
