---
- name: my playbook
  hosts: all
  become: yes
  tasks:
  
  - name: installing httpd package
    yum:
      name: httpd
      state: latest
    when: ansible_os_family == 'RedHat'
    notify: starting httpd service

  - name: installing apache2 package
    apt:
      name: apache2
      state: present
    when: ansible_os_family == 'Debian'
    notify: starting apache2 service

  - name: copying index.html file
    copy:
      src: /home/ansadmin/index.html
      dest: /var/www/html

  handlers:

  - name: deleting httpd package
    yum:
      name: httpd
      state: absent
    when: ansible_os_family == 'RedHat'

  - name: deleting apache2 package
    apt:
      name: apache2
      state: absent
    when: ansible_os_family == 'Debian'

  - name: starting httpd service
    service:
      name: httpd
      state: started
    when: ansible_os_family == 'RedHat'

  - name: starting apache2 service
    service:
      name: apache2
      state: started
    when: ansible_os_family == 'Debian'
